### ISSUE TITLE
iPhone X 기종에서 댓글창 오류 해결하기

### ISSUE THREAD

**Issue by hwanghe159** [woowacourse-teams/2020-saebyeok#212]
### 목적
아래의 사진처럼 iPhone X 기종에서 댓글창이 윗방향이 아닌 아래 방향으로 확장되는 버그가 발생한다.

![image](https://user-images.githubusercontent.com/42054054/94146526-04b62800-feaf-11ea-9f51-ebed3af256af.png)

#### 예상되는 원인
```css
<style>
.navbarSpace {
  height: 76px !important;
  padding-bottom: 20px;
}
</style>
```
iPhone X 기종에선 위와 같이 padding-bottom이 적용됨
아래에 공간이 있으니까 아래로 확장되는 것으로 의심됨.

### 체크리스트
- [ ] iPhone X에서도 댓글창이 위로 자라야 한다.

### 관련 이슈
- 
### 일정
-
